spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        native:
          search-locations: ${CONFIG_REPO_PATH:file:../config-repo}
  profiles:
    active: native

server.port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health,info
